#!/usr/bin/env bash
# =============================================================
# A1 Music App — Interactive Setup Script
# =============================================================
# Usage:  bash scripts/setup.sh
# =============================================================

set -e

# ── Colors ────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# ── Helpers ───────────────────────────────────────────────────
info()    { echo -e "${BLUE}ℹ${NC}  $*"; }
success() { echo -e "${GREEN}✔${NC}  $*"; }
warn()    { echo -e "${YELLOW}⚠${NC}  $*"; }
error()   { echo -e "${RED}✖${NC}  $*"; }
header()  { echo -e "\n${BOLD}${CYAN}$*${NC}\n"; }
prompt()  { echo -e "${YELLOW}?${NC}  $*"; }

# ── Banner ────────────────────────────────────────────────────
clear
echo -e "${BOLD}${CYAN}"
echo "  ╔═══════════════════════════════════════╗"
echo "  ║        A1 Music App  Setup 🎵          ║"
echo "  ╚═══════════════════════════════════════╝"
echo -e "${NC}"
echo "  This script will:"
echo "    • Generate a secure NEXTAUTH_SECRET"
echo "    • Create your .env.local file"
echo "    • Guide you through each required key"
echo ""
echo "  Press ENTER to continue, or Ctrl+C to exit."
read -r

# ── Check prerequisites ───────────────────────────────────────
header "Step 0 — Checking prerequisites"

check_command() {
  if command -v "$1" &> /dev/null; then
    success "$1 found"
  else
    warn "$1 not found — some steps may need manual action"
  fi
}

check_command node
check_command npm
check_command openssl

# ── Generate NEXTAUTH_SECRET ──────────────────────────────────
header "Step 1 — Generating NEXTAUTH_SECRET"

if command -v openssl &> /dev/null; then
  NEXTAUTH_SECRET=$(openssl rand -hex 32)
  success "Generated NEXTAUTH_SECRET using openssl"
elif command -v node &> /dev/null; then
  NEXTAUTH_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  success "Generated NEXTAUTH_SECRET using Node.js"
else
  warn "Cannot auto-generate secret. Please visit: https://generate-secret.vercel.app/32"
  prompt "Paste your secret here:"
  read -r NEXTAUTH_SECRET
fi

echo ""
info "Your NEXTAUTH_SECRET (keep this safe!):"
echo -e "  ${GREEN}${NEXTAUTH_SECRET}${NC}"
echo ""

# ── Collect environment variables ─────────────────────────────
header "Step 2 — Database URL"
echo "  Supported providers:"
echo "    • Supabase (recommended): https://supabase.com"
echo "    • Railway:                https://railway.app"
echo "    • Render:                 https://render.com"
echo ""
echo "  Format: postgresql://user:password@host:5432/dbname"
echo "  See docs/DATABASE_SETUP.md for full instructions."
echo ""
prompt "Paste your DATABASE_URL (or press ENTER to skip for now):"
read -r DATABASE_URL
DATABASE_URL="${DATABASE_URL:-postgresql://user:password@localhost:5432/a1_music}"

header "Step 3 — GitHub OAuth"
echo "  1. Go to: https://github.com/settings/developers"
echo "  2. Click  'New OAuth App'"
echo "  3. Set Authorization callback: http://localhost:3000/api/auth/callback/github"
echo "  4. Copy Client ID and Client Secret"
echo ""
prompt "Paste your GITHUB_ID (or press ENTER to skip):"
read -r GITHUB_ID
GITHUB_ID="${GITHUB_ID:-your_github_client_id}"

prompt "Paste your GITHUB_SECRET (or press ENTER to skip):"
read -r GITHUB_SECRET
GITHUB_SECRET="${GITHUB_SECRET:-your_github_client_secret}"

header "Step 4 — OpenAI API Key"
echo "  1. Go to: https://platform.openai.com/account/api-keys"
echo "  2. Click  'Create new secret key'"
echo "  3. Copy the key immediately (won't show again)"
echo ""
prompt "Paste your OPENAI_API_KEY (or press ENTER to skip):"
read -r OPENAI_API_KEY
OPENAI_API_KEY="${OPENAI_API_KEY:-sk-your_openai_api_key_here}"

header "Step 5 — Application URL"
prompt "Your app URL (press ENTER for http://localhost:3000):"
read -r NEXTAUTH_URL
NEXTAUTH_URL="${NEXTAUTH_URL:-http://localhost:3000}"

# ── Write .env.local ──────────────────────────────────────────
header "Step 6 — Writing .env.local"

ENV_FILE="$(pwd)/.env.local"

cat > "$ENV_FILE" << EOF
# A1 Music App — Local Environment Variables
# Generated by scripts/setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file to version control!

NODE_ENV=development
PORT=3000

# Application URL
NEXTAUTH_URL=${NEXTAUTH_URL}
NEXT_PUBLIC_API_URL=${NEXTAUTH_URL}

# Authentication (auto-generated)
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# GitHub OAuth
GITHUB_ID=${GITHUB_ID}
GITHUB_SECRET=${GITHUB_SECRET}

# OpenAI
OPENAI_API_KEY=${OPENAI_API_KEY}

# Database
DATABASE_URL=${DATABASE_URL}

# Stripe (optional — fill in when ready)
STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key
STRIPE_PUBLISHABLE_KEY=pk_test_your_stripe_publishable_key

# Redis (optional)
REDIS_URL=
EOF

success ".env.local written to: ${ENV_FILE}"

# ── Install dependencies ───────────────────────────────────────
header "Step 7 — Installing dependencies"

if [ -f package.json ]; then
  prompt "Install npm dependencies now? (Y/n):"
  read -r INSTALL_DEPS
  if [[ ! "$INSTALL_DEPS" =~ ^[Nn]$ ]]; then
    npm install
    success "Dependencies installed"
  else
    info "Skipped. Run 'npm install' when ready."
  fi
fi

# ── Summary ────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}╔═══════════════════════════════════════╗"
echo "║         Setup Complete! 🎉             ║"
echo -e "╚═══════════════════════════════════════╝${NC}"
echo ""
echo "  Next steps:"
echo ""
echo "  1. Review your .env.local file"
echo "  2. Fill in any values you skipped"
echo "  3. Run: npm run dev"
echo "  4. Open: http://localhost:3000"
echo ""
echo "  📚 Guides:"
echo "     docs/QUICK_START.md         — 5-minute launch guide"
echo "     docs/GET_API_KEYS.md        — How to get API keys"
echo "     docs/DATABASE_SETUP.md      — Database setup"
echo "     docs/DEPLOYMENT_CHECKLIST.md — Pre-launch checklist"
echo ""
echo "  🚀 Ready to deploy?"
echo "     Follow: docs/QUICK_START.md"
echo ""
