#!/usr/bin/env node
/**
 * A1 Music App — Interactive Setup Script (Node.js)
 *
 * Use this if you don't have bash available (e.g., Windows without WSL).
 *
 * Usage:  node scripts/setup.js
 */

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const readline = require("readline");

// ── Colors (ANSI) ─────────────────────────────────────────────
const c = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  blue: "\x1b[34m",
  cyan: "\x1b[36m",
  red: "\x1b[31m",
};

const info = (msg) => console.log(`${c.blue}ℹ${c.reset}  ${msg}`);
const success = (msg) => console.log(`${c.green}✔${c.reset}  ${msg}`);
const warn = (msg) => console.log(`${c.yellow}⚠${c.reset}  ${msg}`);
const header = (msg) =>
  console.log(`\n${c.bold}${c.cyan}${msg}${c.reset}\n`);

// ── Readline helper ───────────────────────────────────────────
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function ask(question, defaultValue = "") {
  return new Promise((resolve) => {
    const hint = defaultValue ? ` (press ENTER for default)` : "";
    rl.question(`${c.yellow}?${c.reset}  ${question}${hint}: `, (answer) => {
      resolve(answer.trim() || defaultValue);
    });
  });
}

// ── Main ──────────────────────────────────────────────────────
async function main() {
  console.clear();
  console.log(`${c.bold}${c.cyan}`);
  console.log("  ╔═══════════════════════════════════════╗");
  console.log("  ║        A1 Music App  Setup 🎵          ║");
  console.log(`  ╚═══════════════════════════════════════╝${c.reset}`);
  console.log("");
  console.log("  This script will:");
  console.log("    • Generate a secure NEXTAUTH_SECRET");
  console.log("    • Create your .env.local file");
  console.log("    • Guide you through each required key");
  console.log("");

  await ask("Press ENTER to continue");

  // Step 1 — Generate secret
  header("Step 1 — Generating NEXTAUTH_SECRET");
  const NEXTAUTH_SECRET = crypto.randomBytes(32).toString("hex");
  success("Generated NEXTAUTH_SECRET");
  info(`Your secret: ${c.green}${NEXTAUTH_SECRET}${c.reset}`);

  // Step 2 — Database
  header("Step 2 — Database URL");
  console.log("  Supported providers:");
  console.log(
    "    • Supabase (recommended): https://supabase.com"
  );
  console.log("    • Railway:                https://railway.app");
  console.log("    • Render:                 https://render.com");
  console.log("");
  console.log(
    "  Format: postgresql://user:password@host:5432/dbname"
  );
  console.log("  See docs/DATABASE_SETUP.md for full instructions.");
  console.log("");
  const DATABASE_URL = await ask(
    "Paste your DATABASE_URL (or ENTER to skip)",
    "postgresql://user:password@localhost:5432/a1_music"
  );

  // Step 3 — GitHub OAuth
  header("Step 3 — GitHub OAuth");
  console.log("  1. Go to: https://github.com/settings/developers");
  console.log("  2. Click  'New OAuth App'");
  console.log(
    "  3. Set Authorization callback: http://localhost:3000/api/auth/callback/github"
  );
  console.log("  4. Copy Client ID and Client Secret");
  console.log("");
  const GITHUB_ID = await ask(
    "Paste your GITHUB_ID (or ENTER to skip)",
    "your_github_client_id"
  );
  const GITHUB_SECRET = await ask(
    "Paste your GITHUB_SECRET (or ENTER to skip)",
    "your_github_client_secret"
  );

  // Step 4 — OpenAI
  header("Step 4 — OpenAI API Key");
  console.log(
    "  1. Go to: https://platform.openai.com/account/api-keys"
  );
  console.log("  2. Click  'Create new secret key'");
  console.log("  3. Copy the key immediately (won't show again)");
  console.log("");
  const OPENAI_API_KEY = await ask(
    "Paste your OPENAI_API_KEY (or ENTER to skip)",
    "sk-your_openai_api_key_here"
  );

  // Step 5 — App URL
  header("Step 5 — Application URL");
  const NEXTAUTH_URL = await ask(
    "Your app URL",
    "http://localhost:3000"
  );

  // Step 6 — Write file
  header("Step 6 — Writing .env.local");

  const envPath = path.join(process.cwd(), ".env.local");
  const envContent = `# A1 Music App — Local Environment Variables
# Generated by scripts/setup.js on ${new Date().toISOString()}
# DO NOT commit this file to version control!

NODE_ENV=development
PORT=3000

# Application URL
NEXTAUTH_URL=${NEXTAUTH_URL}
NEXT_PUBLIC_API_URL=${NEXTAUTH_URL}

# Authentication (auto-generated)
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# GitHub OAuth
GITHUB_ID=${GITHUB_ID}
GITHUB_SECRET=${GITHUB_SECRET}

# OpenAI
OPENAI_API_KEY=${OPENAI_API_KEY}

# Database
DATABASE_URL=${DATABASE_URL}

# Stripe (optional — fill in when ready)
STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key
STRIPE_PUBLISHABLE_KEY=pk_test_your_stripe_publishable_key

# Redis (optional)
REDIS_URL=
`;

  fs.writeFileSync(envPath, envContent, "utf8");
  success(`.env.local written to: ${envPath}`);

  // Summary
  rl.close();
  console.log("");
  console.log(
    `${c.bold}${c.green}╔═══════════════════════════════════════╗`
  );
  console.log("║         Setup Complete! 🎉             ║");
  console.log(`╚═══════════════════════════════════════╝${c.reset}`);
  console.log("");
  console.log("  Next steps:");
  console.log("");
  console.log("  1. Review your .env.local file");
  console.log("  2. Fill in any values you skipped");
  console.log("  3. Run: npm run dev");
  console.log("  4. Open: http://localhost:3000");
  console.log("");
  console.log("  📚 Guides:");
  console.log(
    "     docs/QUICK_START.md          — 5-minute launch guide"
  );
  console.log(
    "     docs/GET_API_KEYS.md         — How to get API keys"
  );
  console.log(
    "     docs/DATABASE_SETUP.md       — Database setup"
  );
  console.log(
    "     docs/DEPLOYMENT_CHECKLIST.md — Pre-launch checklist"
  );
  console.log("");
  console.log("  🚀 Ready to deploy? Follow: docs/QUICK_START.md");
  console.log("");
}

main().catch((err) => {
  console.error(`${c.red}Error:${c.reset} ${err.message}`);
  process.exit(1);
});
